### PR TITLE
Fixing SuperResolution implementation, adding RTX Video HDR, and other small fixes

### PR DESCRIPTION
**Pull request by JTGaming**
Fixed SuperResolution so it now behaves more nicely on HDR screens, is only enabled when it is supported, and the debug screen more closely shows when it is actually active.
Added support for RTX Video HDR for videos that can use this feature. There's also a UI button for it, and it shows up on the debug screen when it's in use.
Fixed an issue where dragging an HDR window from an SDR screen to an HDR screen before the video has initialized would default the window to SDR mode.
Fixed an issue where toggling from fullscreen to windowed mode on a multi-monitor setup would make the renderer think we swapped monitors.
Turning off HDR passthrough in UI now resets the window to SDR.
Realigned some options in the UI.

I've tried to keep every commit commented so it should be easy to see what each change is doing.

### CODE REVIEW

**Comment by Aleksoid1978** [comment]
I repeat, I don’t know how many times - until the developers have the appropriate video cards with support for SuperRes / Nvidia RTV Video HDR - there will be no changes in the code.

Well, even more so such requests in which everything is in a heap - here there are SuperRes and Nvidia RTV Video HDR and some changes in the UI.

**Comment by Aleksoid1978** [comment]
Let this request remain open for now - for the future.

**Review by v0lt — APPROVED** [review]

**Comment by v0lt** [comment]
Thanks for the detailed pull request. We will analyze the patches and accept some of the changes, but not quickly.

I don’t know how to accept individual commits here, so I will make changes myself with attribution.

**Comment by Aleksoid1978** [comment]
Can you make a separate pull request just for RTX HDR ?

**Comment by Aleksoid1978** [comment]
I made my own implementation of this functionality.

**Pull request closed without merging**
