### PR TITLE
Added key features list

### PR DESCRIPTION
**Pull request by Tarek-Hasan**
Translated from MPC Video Renderer forum post

### CODE REVIEW

**Comment by Aleksoid1978** [comment]
**- Supports DXVA2 and Direct3D 11 hardware decoding.** - Video renderer don't do any decoding.
**- Supports subtitle output in conjunction with MPC-BE.** - Not only with MPC-BE
**- Chroma scaling algorithm for increasing the color component from 4:2:0 and 4:2:2 to 4:4:4.** - There's no such thing.

**Comment by Tarek-Hasan** [comment]
- I will remove 1 & 2
- and modify 3rd point further 2 point
  - Chroma Sampling
  - Video Shader Upscaling/Downscaling

**Comment by hooke007** [comment]
> Chroma Sampling

Any video renderer would do this job. It doesn't matter at all.

**Comment by v0lt** [comment]
I'll add something similar to the Readme.md this month.

**Pull request closed without merging**
